# -*- coding: utf-8 -*-
"""crawl-stream.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F4YIOQ_wnEp3rCkty4FQZYYOFvD8aUyu
"""

from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream
import datetime
import json, time, sys
import csv
import telegram

# API Twitter
consumer_key = '6qXA2fmtgpN68yQSy3IzLUPs6'
consumer_secret = '0TEL9W6Eh3Dumx54zAdDWj2lA2i88ookST5jucs0ZOpQmwAb6m'
access_token = '563053721-yCvEBd3vxKWjxqNeJnQ4dRpMw3nEiPX1kfMbny5r'
access_token_secret = 'R99YPN00JTRZF7hNEnH9SkjoDJRn4UhGawdibX0cy1RGq'

# API Telegram
api_key = '2010624549:AAGHEwhPkNtjLMFWjY3BpLtkXytWT8LDrCg'
user_id = '-1001735202458'

auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

class StdOutListener(StreamListener):
    def __init__(self, api=None):
        super(StdOutListener, self).__init__()
        self.num_tweets = 0     # buat variabel inisialisasi jumlah tweet

    def on_status(self, status):
        # record = {'TWEET': status.text, 'LINK': 'https://twitter.com/'+str(status.user.screen_name)+'/status/'+str(status.id)}       # simpan hasil response kedalam variabel (contoh: ambil text/tweet dan created_at/tanggal tweet)
        tweet = status.text
        link = 'https://twitter.com/'+str(status.user.screen_name)+'/status/'+str(status.id)
        username = str(status.user.screen_name)
        if (username == 'joktugfess' or username == 'basejokitugas') :
            bot = telegram.Bot(token=api_key)
            record = bot.send_message(chat_id=user_id, text=tweet + " " + link)
            print(record)
          
        self.num_tweets += 1        # setiap satu tweet yang berhasil didapat dihitung dengan menambahkan satu
        if status.lang == 'in':     # filter tweet yang hanya berbahasa indonesia
          if self.num_tweets < 200:  # batasi jumlah tweet yang dicrawling sebanyak 20
              return True
          else:
              return False

    def on_error(self, status_code):
        if status_code == 420:
            print('Error on status', status)
            return False

    def on_limit(self, status):
        print('Limit threshold exceeded', status)

    def on_timeout(self, status):
        print('Stream disconnected; continuing...')


stream = Stream(auth, StdOutListener())
# stream.filter(follow=["1330354354780577792"]) # akun twitter untuk di scrape
stream.filter(track=['coding', 'joki buat program', 'joki program', 'joki ngoding', 'joki data mining', 'buat flowchart', 'bikin flowchart', 'bantuin bikin logo', 'bantuin bikin poster', 'bantuin bikin banner', 'joki coding', 'tugas coding', 'joki informatika', 'joki pemrograman', 'joki java', 'bantuin java', 'bantuin c++', 'bantuin python', 'tugas python', 'joki python'])   # menggunakan fungsi stream filter untuk mencari kata kunci
# stream.filter(track=['joktug!', 'bj!', 'Bj!', 'BJ!'])   # menggunakan fungsi stream filter untuk mencari kata kunci